### ISSUE TITLE
Download very slow for Windows

### ISSUE THREAD

**Issue by FabianVista** [olivierhagolle/LANDSAT-Download#12]
Hi Olivier,

after some testing everything works fine for me on Windows as well as on Linux. There remains just one issue regarding the download speed on Windows. Compared to Linux it is much slower (factor 10 ~200KB/s to 2MB/s), even though the Linux OS is implemented on a Virtual Machine on the same Desktop as Windows(so both are connected to the same Network).
I am not a python expert, so do you have any clue what this might cause?
Thanks,

Fabian

**Comment by olivierhagolle** [comment]
Dear Fabian,
I am sorry, I never use windows !
Olivier

**Comment by FabianVista** [comment]
Thanks anyway!

**Comment by mkmitchell** [comment]
I was downloading at only 50kb/s using the chunk method in windows.  I changed the code to check the platform and simply used
fp.write(req.read())
instead of the chunk method and now I'm downloading at normal seeds (400kb/s).  I don't have the nice pretty download status bar but it works.  I may try to track down the issue a bit more and create a branch for future windows users.

**Comment by mkmitchell** [comment]
Upon further inspection it appears that in windows the file is being downloaded at good speeds but the status bar is reporting that speed incorrectly.

**Comment by olivierhagolle** [comment]
Thanks Mike. I think the status bar is reporting kB/s (kiloBytes per second), which would explain the factor  you observed.
