### ISSUE TITLE
Error downloading LC8 images

### ISSUE THREAD

**Issue by jens2121** [olivierhagolle/LANDSAT-Download#31]
Hi there,

I am getting an error and don't know the actual issue?
The query I run is as follows:
"E:\xx_2_Python_Automation_Scripts\TEMP\Automated_Download_LANDSAT\LANDSAT-Download-master>download_landsat_scene.py -o scene -b LC8 -d 20161001 -s 170073 -u E:\xx_2_Python_Automation_Scripts\TEMP\Automated_Download_LANDSAT\LANDSAT-Download-master\usgs.txt --output E:\xx_2_Python_Automation_Scripts\TEMP\Automated_Download_LANDSAT\TEST_OUTPUTS"

And the error that comes up is the following:
"Searching for images on (julian date): 2016278...
http://earthexplorer.usgs.gov/download/4923/LC81700732016278LGN00/STANDARD/EE
error : file is in html and not an expected binary file
result saved in ./error_output.html
   product LC81700732016278LGN00 not found
http://earthexplorer.usgs.gov/download/4923/LC81700732016278LGN01/STANDARD/EE
http://earthexplorer.usgs.gov/download/4923/LC81700732016278LGN02/STANDARD/EE
Searching for images on (julian date): 2016294...
http://earthexplorer.usgs.gov/download/4923/LC81700732016294LGN00/STANDARD/EE
error : file is in html and not an expected binary file
result saved in ./error_output.html
   product LC81700732016294LGN00 not found
http://earthexplorer.usgs.gov/download/4923/LC81700732016294LGN01/STANDARD/EE
http://earthexplorer.usgs.gov/download/4923/LC81700732016294LGN02/STANDARD/EE"

Not too sure why it is failing to find the results.

Thanks!

**Comment by olivierhagolle** [comment]
Hi Jens,
I was having the same issue on my side, and changed the script last week.
Are you using the very last version ?

Earthexplorer site is down today, I can't try your command line
Olivier

**Comment by jens2121** [comment]
Hi Olivier.

Thanks for your response!

I actually had some success earlier today before USGS scheduled maintenance.

I will try again tomorrow and give you feedback. Awesome script and thank you.

Best,
Jens



Sent from my Samsung device


-------- Original message --------

**Comment by TvanNiel** [comment]
Hi Olivier and Jens,

I get this same error message.  Did either of you figure out what the problem was?  

Here is an example of what I run from a Jupyter notebook:
----------------------------------------------------------------------------------
%run download_landsat_scene.py -o scene -b LC8 -d 20161001 -s 111076 -u usgs.txt --output ../data
----------------------------------------------------------------------------------

It was running yesterday, but today I get the following message:
----------------------------------------------------------------------------------
None None
Searching for images on (julian date): 2016281...
http://earthexplorer.usgs.gov/download/4923/LC81110762016281LGN00/STANDARD/EE
error : file is in html and not an expected binary file
result saved in ./error_output.html
   product LC81110762016281LGN00 not found
http://earthexplorer.usgs.gov/download/4923/LC81110762016281LGN01/STANDARD/EE
http://earthexplorer.usgs.gov/download/4923/LC81110762016281LGN02/STANDARD/EE
Searching for images on (julian date): 2016297...
http://earthexplorer.usgs.gov/download/4923/LC81110762016297LGN00/STANDARD/EE
error : file is in html and not an expected binary file
result saved in ./error_output.html
   product LC81110762016297LGN00 not found
http://earthexplorer.usgs.gov/download/4923/LC81110762016297LGN01/STANDARD/EE
http://earthexplorer.usgs.gov/download/4923/LC81110762016297LGN02/STANDARD/EE
Searching for images on (julian date): 2016313...
http://earthexplorer.usgs.gov/download/4923/LC81110762016313LGN00/STANDARD/EE
error : file is in html and not an expected binary file
result saved in ./error_output.html
   product LC81110762016313LGN00 not found
http://earthexplorer.usgs.gov/download/4923/LC81110762016313LGN01/STANDARD/EE
http://earthexplorer.usgs.gov/download/4923/LC81110762016313LGN02/STANDARD/EE
----------------------------------------------------------------------------------

If I copy and paste the URL into my web browser manually, it downloads it.  For example, copying and pasting the following address downloads the image:
----------------------------------------------------------------------------------
http://earthexplorer.usgs.gov/download/4923/LC81110762016281LGN00/STANDARD/EE
----------------------------------------------------------------------------------

**Comment by olivierhagolle** [comment]
Dear TvanNIel, 
I just tried your command line with the very last version of the tool I updated two weeks ago. 
It works for me. Maybe there was something wrong with the site ?
Did you try to read the error_output.html file which is created ?

My recommendation would be
- update the script
- try again
- in case it does not work, read the output.html and tell me

Best regards,
Olivier

**Comment by TvanNiel** [comment]
Hi Olivier,

It's a bit of a mystery.  I already had the latest version of the script so I've just tried again and it is now working.  I'm not sure why copying and pasting the URL into my web browser would work yesterday, but the script wouldn't.  Anyway, the script is working now.  Thanks for your consideration.

Cheers,
Tom
